name: "test_add_uncertainty"
group: "test"
output_dir: "tests/test_add_uncertainty/outputs/"
model: "UNet"
uncertainty_type: "softmax"
alpha: 0.1
delta: 0.1
num_lambdas: 20
rcps_loss: "fraction_missed"
q_lo: 0.05
q_hi: 0.95
q_lo_weight: 1
q_hi_weight: 1
minimum_lambda: 0 
maximum_lambda: 10
mse_weight: 1
num_validation_images: 5 
device: "cuda"
device_ids: [0,1]
epochs: 10 
batch_size: 8 
lr: 0.0001
load_from_checkpoint: True
input_normalization: "standard"
output_normalization: "min-max"
